### PR TITLE
Setting appropriate content-type in filters example

### PR DESCRIPTION
**Pull request by Eternity-Yarr**
we select which content-type will be sent to the user based on request path and jsonp request parameter

### CODE REVIEW

**Comment by Ogeon** [comment]
...still, it's more correct. I'll take an other look at it tomorrow, when I'm not this tired, but it looks good.

**Comment by Ogeon** [comment]
I'll also fix the error from AppVeyor... Again.

**Comment by Eternity-Yarr** [comment]
Looks like it's not AppVeyor fault, but slproweb simply replaced 1_0_2d with 1_0_2e version of openSSL :

404 https://slproweb.com/download/Win32OpenSSL-1_0_2d.exe 
200 https://slproweb.com/download/Win32OpenSSL-1_0_2e.exe

**Comment by Ogeon** [comment]
Yeah, that's what I meant. There's unfortunately no way to just get the latest version...

**Comment by Ogeon** [comment]
Looks like rand is also broken now. I'll put this on hold and see how things plays out.

**Comment by Eternity-Yarr** [comment]
Seems like it s a new nightly :) not the same my build was failed on.

**Comment by Eternity-Yarr** [comment]
retry ?

**Comment by Ogeon** [comment]
Nah, @homu will only listen to me at the moment :), but I restarted the tests manually. I haven't had the time to fix things yet...

**Comment by Ogeon** [comment]
#90 contains the necessary changes. It looks like `rand` has been updated to work with nightly, so that's good, but I had to do a very fundamental change to `insert_routes!` to avoid the type ascription conflict.

I would also like to point you to #89 and ask you if you agree to dual license this PR and any future contributions to Rustful under MIT/Apache, as described there. I don't know when (or if) the relicensing will happen, so there is a chance that you will count as a "creative contributor" before it's done.

**Comment by Ogeon** [comment]
There we go. It's merged now, so you can rebase this PR and we can continue as before :smile:

**Comment by Eternity-Yarr** [comment]
Sure, i do agree with dual license, but i'm not sure if my pr is somewhat creative.

**Comment by Ogeon** [comment]
Alright :smile: It's not only for this, but for any potential future contributions as well.

Anyway, I see that you have rebased and the tests looks good, but what about the jsonp variant? I think the correct content type for it is `application/javascript`.

**Comment by Eternity-Yarr** [comment]
Sure, i'll add special case for jsonp. But this will require some refactoring of this particular test

**Comment by Ogeon** [comment]
Sure, go ahead.

**Comment by Eternity-Yarr** [comment]
(not to mention http://localhost:8080/json/Peter%22 case). I think working around this kind of issues would be an overkill for little example.

**Comment by Ogeon** [comment]
Hmm, yeah, its primary feature is to showcase filters. It doesn't have to be 100% correct in every case, but I just thought that adding a content type for one case and not the rest would be stranger than keeping it as it is...

**Comment by Eternity-Yarr** [comment]
Yeah, let's hope that no one  would actually use it as reference for his own json rest service :))

**Comment by Ogeon** [comment]
Haha, yeah. It's not great, but it's also hard to make simple examples of complex things. You are very welcome to play around with it if you happen to have any more ideas for improvements. That goes for every example here, really.

**Comment by Eternity-Yarr** [comment]
Sure, I'll try to do something tomorrow.

**Comment by Eternity-Yarr** [comment]
I've tried to do it as less intrusive as possible, because I'm new no the Rust.

**Comment by Ogeon** [comment]
Oh, interesting approach. My first impression is that I like it. :smile: It's once again late over here, so I will wait with the decision until tomorrow.

Also, don't worry about being new to Rust. I'll do my best to be a good mentor.

**Comment by Ogeon** [comment]
I have read through it now and I think it's good. I think this change is small enough to be squashed into one single commit, since the two solutions are quite different.

Would you also mind summarizing the changes in the top comment? It's what will go into the final commit message and will help anyone looking back on this to understand what happened. It doesn't have to be fancy. Just to answer the "how?" question.

**Comment by Eternity-Yarr** [comment]
You mean 'edit top comment of this pr' ?

**Comment by Ogeon** [comment]
Yes, since that's what people will read first. It's just so they don't have to wrap their heads around the code. This will do :smile: 

Thanks!

@homu r+

**Comment by Ogeon** [comment]
@homu r+

**Comment by Ogeon** [comment]
Hmm... is @homu asleep?

**Comment by Ogeon** [comment]
Looks like it. I'll merge this myself, then. It's ok if it doesn't make it into the change log.

**Pull request merged**
