### PR TITLE
Cleanup some warnings from Clippy

### PR DESCRIPTION
**Pull request by mcarton**
For information, [here is the log before and after](https://gist.github.com/mcarton/6411c8526dee7b12632b) with Clippy.
Remaining warnings from Clippy are mostly false positive.

### CODE REVIEW

**Comment by Ogeon** [comment]
Ah, nice! Some, if not many, of those are old relics from when Rust was different... Nice to see them being found and cleaned out. I guess I should start checking with Clippy from time to time.

Some of the remaining ones are most likely necessary or doesn't really matter, but at least the last once about `&Vec<...>` sounds like it can be safely fixed. I can't imagine a reason for doing like that, except a brain slip. I'm fine with leaving them as they are for now, unless you want to give it another go.

**Comment by mcarton** [comment]
I wasn't sure about that one since it changes some public interface.

**Comment by Ogeon** [comment]
No, that one is safe to change. I have hidden it from the docs and written a warning.

**Comment by Ogeon** [comment]
The tests are nice and green. Thank you!

@homu r+

**Pull request merged**
