### PR TITLE
OpenSSL version bumped

### PR DESCRIPTION
**Pull request by Eternity-Yarr**
Hey, AppVeyor, try this one?

### CODE REVIEW

**Comment by Eternity-Yarr** [comment]
```
12:02 < Yurume> i_rony|nb: okay! I now understood what happened.
12:02 < Yurume> the nightly compiler has a new syntax `expr: T` (type ascription, used to annotate the intermediate expr)
12:03 < Yurume> rustful has a series of macros that is not prepared of this addition, so `Get: Greeting("hello")` is treated as if `Get: Greeting` (a 
                legitimiate expression) and a stray `("hello")`
12:03 < Yurume> (or `Greeting("hello")` being parsed as a type)
```

**Comment by Ogeon** [comment]
Oh my... I'm glad to see that type ascriptions are on their way. This conflict should be fairly easy to get around by taking a `tt` as the method, unless I'm missing something. It would be a breaking change, but that's true for the alternatives as well.

**Comment by Eternity-Yarr** [comment]
Well, then.. It's unlikely that I would be able to make this change in reasonable amount of time :) , so I will close this pr, and stare at macros for a while.

**Comment by Ogeon** [comment]
It's alright. I'll try to get this sorted out as fast as possible, but I'm still enjoying the company of my family, so my free time is a bit unpredictable. You are still free to give it a try if you want to.

**Pull request closed without merging**
