### PR TITLE
Remove support for rustc-serialize

### LINKED ISSUE #123: Remove support for rustc-serialize
`rustc-serialize` [has been deprecated](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485) so there's no longer any good reasons to maintain built-in support for it.

### PR DESCRIPTION
**Pull request by xliiv**
Replace `rustc-serialize` integration with `serde_json`.
Breaking changes:
- removing `read_json_body` & `decode_json_body` from `BodyReader`

Fixes #123

### CODE REVIEW

**Comment by Ogeon** [comment]
If you write "Fixes #issuenumber" or "Closes #issuenumber" in your pull request description it will link and close it automatically.

**Comment by xliiv** [comment]
Btw: this needs squashing

**Comment by Ogeon** [comment]
I'll do it when I'm merging.

**Comment by Ogeon** [comment]
By the way, just to be clear, the fixes or closes thing can be anywhere in the description, so you can write something more elaborate if you want to. Let me know when you are satisfied. :smile:

**Comment by xliiv** [comment]
I'll write something :)

**Comment by xliiv** [comment]
To me it's ready ;)

**Comment by Ogeon** [comment]
Hold on, I missed that you put the serde dependencies under `[dependencies]`. They are only used in the example, so they should go under `[dev-dependencies]`. Sorry about that.

**Comment by xliiv** [comment]
It's ok, I'll fix it.

**Comment by Ogeon** [comment]
Perfect! I'll merge when the tests are green. Thanks!

**Comment by xliiv** [comment]
cool :)

**Pull request merged**
